export const THREADS_API_BASE = 'https://graph.threads.net/v1.0';

export const API_ERROR_CODES = {
  // 인증 오류
  INVALID_ACCESS_TOKEN: 190,
  API_SESSION_EXPIRED: 102,
  APP_NOT_INSTALLED: 458,
  PASSWORD_CHANGED: 460,
  TOKEN_EXPIRED: 463,
  INVALID_ACCESS_TOKEN_2: 467,
  INVALID_SESSION: 492,

  // API 호출 제한
  TOO_MANY_CALLS: 4,
  TOO_MANY_USER_CALLS: 17,
  APP_LIMIT_REACHED: 341,

  // 권한 부족
  PERMISSION_DENIED: 10,
  API_PERMISSION_ERROR: 200,

  // 일시적 장애
  UNKNOWN_API: 1,
  SERVICE_UNAVAILABLE: 2,
} as const;

export const STATUS_CODE_MAP: Record<number, number> = {
  // 인증 오류: 401 Unauthorized
  [API_ERROR_CODES.INVALID_ACCESS_TOKEN]: 401,
  [API_ERROR_CODES.API_SESSION_EXPIRED]: 401,
  [API_ERROR_CODES.APP_NOT_INSTALLED]: 401,
  [API_ERROR_CODES.PASSWORD_CHANGED]: 401,
  [API_ERROR_CODES.TOKEN_EXPIRED]: 401,
  [API_ERROR_CODES.INVALID_ACCESS_TOKEN_2]: 401,
  [API_ERROR_CODES.INVALID_SESSION]: 401,

  // API 호출 제한: 429 Too Many Requests
  [API_ERROR_CODES.TOO_MANY_CALLS]: 429,
  [API_ERROR_CODES.TOO_MANY_USER_CALLS]: 429,
  [API_ERROR_CODES.APP_LIMIT_REACHED]: 429,

  // 권한 부족: 403 Forbidden
  [API_ERROR_CODES.PERMISSION_DENIED]: 403,
  [API_ERROR_CODES.API_PERMISSION_ERROR]: 403,

  // 일시적 장애: 503 Service Unavailable
  [API_ERROR_CODES.UNKNOWN_API]: 503,
  [API_ERROR_CODES.SERVICE_UNAVAILABLE]: 503,
};
